language: java
sudo: false
addons:
    apt:
        packages:
            - ant
            - jing
before_install:
    - git clone --depth=1 https://github.com/TEIC/Stylesheets.git

before_script:
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ all

script:
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ test