language: generic # don't install any environment

env:
  global:
    - PATH_TO_SAXON_JAR: Saxon-HE-9.6.0-7.jar
    - PATH_TO_JING: /usr/bin/jing
    - PATH_TO_TEI_STYLESHEETS: $TRAVIS_BUILD_DIR/Stylesheets
    - ENCRYPTION_LABEL: "73e61484bb4d"
    - COMMIT_AUTHOR_EMAIL: "andrew.hankinson@gmail.com"
# Pin the stylesheets to v7.41.0 (commit c3e4...)
script:
    - ./deploy-docs.sh