language: java
sudo: false
addons:
    apt:
        packages:
            - ant
            - jing
            - libsaxon-java
before_install:
    - git clone --depth=1 https://github.com/TEIC/Stylesheets.git

before_script:
    - ls -alh /usr/bin
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ build

script:
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ test